live_config_reload = true

[shell]
program = "/bin/zsh"

[selection]
semantic_escape_chars = "|:\"' {}()[]<>"
save_to_clipboard = true

[window]
opacity = 0.9
padding = { x = 10, y = 10 }
startup_mode = "Maximized"
title = "Terminal"

[font]
size = 13
normal = { family = "Hack Nerd Font", style = "Regular" }
bold = { family = "Hack Nerd Font", style = "Bold" }
italic = { family = "Hack Nerd Font", style = "Italic" }
bold_italic = { family = "Hack Nerd Font", style = "Bold Italic" }

[colors]
draw_bold_text_with_bright_colors = true
primary = { background = "0x1e2127", foreground = "0xabb2bf", bright_foreground = "0xe6efff" }
normal = { black = "0x1e2127", red = "0xe06c75", green = "0x98c379", yellow = "0xd19a66", blue = "0x61afef", magenta = "0xc678dd", cyan = "0x56b6c2", white = "0x828791" }
bright = { black = "0x5c6370", red = "0xe06c75", green = "0x98c379", yellow = "0xd19a66", blue = "0x61afef", magenta = "0xc678dd", cyan = "0x56b6c2", white = "0xe6efff" }
dim = { black = "0x1e2127", red = "0xe06c75", green = "0x98c379", yellow = "0xd19a66", blue = "0x61afef", magenta = "0xc678dd", cyan = "0x56b6c2", white = "0x828791" }


[cursor]
unfocused_hollow = true
style = { shape = "Beam" }

[keyboard]
bindings = [
  { key = "T", mods = "Control|Shift", command = { program = "sh", args = [ "-c", "tmux neww -c '#{pane_current_path}'" ] } },
  { key = "Right", mods = "Control|Shift", command = { program = "sh", args = [ "-c", "tmux split-pane -hc '#{pane_current_path}'" ] } },
  { key = "Down", mods = "Control|Shift", command = { program = "sh", args = [ "-c", "tmux split-pane -vc '#{pane_current_path}'" ] } },
  { key = "W", mods = "Control|Shift", command = { program = "sh", args = [ "-c", "tmux kill-pane" ] } },
]
